# Generated by Django 4.2.7 on 2024-06-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Establecimiento', 'verbose_name_plural': 'Establecimientos'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número de Mesa')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodirectory.establishment', verbose_name='Establecimiento')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
    ]
