# Generated by Django 4.2.7 on 2024-06-08 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodirectory', '0002_alter_establishment_options_alter_locality_options_and_more'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodirectory.table', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='party_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='party_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numero de lista'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='president',
            field=models.CharField(max_length=100, verbose_name='Presidente'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='vice_president',
            field=models.CharField(max_length=100, verbose_name='Vice-presidente'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dni',
            field=models.PositiveIntegerField(unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False, verbose_name='Votó'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
    ]
