# Generated by Django 4.2.7 on 2024-06-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_politicalparty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='representative_color',
            field=models.CharField(choices=[('WHITE', 'Blanco'), ('RED', 'Rojo'), ('BLUE', 'Azul'), ('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('BLACK', 'Negro')], default='WHITE', max_length=6, verbose_name='Color representativo'),
        ),
    ]
