# Generated by Django 4.2.7 on 2024-06-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodirectory', '0003_remove_table_establishment'),
        ('voting', '0005_politicalparty_representative_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='table',
        ),
        migrations.AddField(
            model_name='voter',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodirectory.establishment', verbose_name='Establecimiento'),
        ),
    ]
