# Generated by Django 4.2.7 on 2024-06-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_voting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicalparty',
            options={'verbose_name': 'Partido Politico', 'verbose_name_plural': 'Partidos Politicos'},
        ),
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name': 'Votante', 'verbose_name_plural': 'Votantes'},
        ),
    ]
